"""Groq LLM-based detection signal."""

import json
import re

from groq import Groq

from config import GROQ_API_KEY, GROQ_MODEL

SYSTEM_PROMPT = """You are an expert at distinguishing human-written text from AI-generated text.
Analyze the provided text and assess the probability that it was generated by an AI language model
(as opposed to being written by a human).

Consider: formulaic transitions ("Furthermore", "It is important to note"), uniform sentence structure,
balanced hedging, lack of personal idiosyncrasy, and overly polished prose.

Respond with ONLY valid JSON in this exact format:
{"ai_probability": <float 0.0-1.0>, "reasoning": "<one sentence>"}

Where ai_probability is your estimate that the text is AI-generated (0.0 = definitely human, 1.0 = definitely AI)."""


def _parse_llm_response(content: str) -> float:
    content = content.strip()
    try:
        data = json.loads(content)
        score = float(data["ai_probability"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        pass

    match = re.search(r"ai_probability[\"']?\s*:\s*([0-9.]+)", content)
    if match:
        return max(0.0, min(1.0, float(match.group(1))))

    return 0.5


def _heuristic_llm_fallback(text: str) -> float:
    """Offline fallback when Groq API is unavailable (development/testing)."""
    ai_markers = [
        "paradigm shift",
        "it is important to note",
        "furthermore",
        "stakeholders",
        "in conclusion",
        "delve",
        "landscape",
        "multifaceted",
        "leverage",
        "utilize",
        "comprehensive",
        "robust",
        "seamless",
    ]
    text_lower = text.lower()
    marker_count = sum(1 for m in ai_markers if m in text_lower)

    casual_markers = [
        "lol",
        "tbh",
        "honestly?",
        "ok so",
        "way too",
        "like three hours",
        "probably won't",
        "idk",
        "ngl",
    ]
    casual_count = sum(1 for m in casual_markers if m in text_lower)

    if casual_count >= 2:
        return 0.15
    if marker_count >= 3:
        return 0.88
    if marker_count >= 1:
        return 0.72
    return 0.45


def analyze_llm(text: str) -> tuple[float, str]:
    """
    Run LLM-based AI detection.

    Returns:
        (llm_score, reasoning) where llm_score is in [0, 1], higher = more likely AI.
    """
    if not GROQ_API_KEY:
        return _heuristic_llm_fallback(text), "fallback: no API key configured"

    client = Groq(api_key=GROQ_API_KEY)
    try:
        response = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {
                    "role": "user",
                    "content": f"Analyze this text:\n\n{text[:4000]}",
                },
            ],
            temperature=0.1,
            max_tokens=150,
        )
        content = response.choices[0].message.content or ""
        score = _parse_llm_response(content)

        reasoning = "parsed from LLM response"
        try:
            reasoning = json.loads(content.strip()).get("reasoning", reasoning)
        except (json.JSONDecodeError, AttributeError):
            pass

        return score, reasoning
    except Exception as exc:
        fallback = _heuristic_llm_fallback(text)
        return fallback, f"API error fallback: {exc}"
